/**
 * Canonical asset index resolver (deadrot.com#343).
 *
 * One stable contract for resolving Deadrot media. The committed
 * `assets.index.json` (generated by `scripts/generate-asset-index.mjs`) lists
 * every shipped asset; this module is the typed front door consumers use
 * instead of hardcoding folder conventions:
 *
 * - {@link resolveAssetPath} → package-relative path, for dev/build tooling
 *   (Vite, `assetgen`, desktop) that reads bytes off disk.
 * - {@link resolveAssetUrl} → absolute CDN URL, for deployed runtime. The base
 *   origin is taken from an explicit `baseUrl`, then the `ASSET_BASE_URL`
 *   environment variable, then the manifest's baked-in {@link AssetIndex.cdnBase}.
 *
 * The resolver is environment-agnostic: it reads `process.env` defensively so
 * it is safe to bundle for the browser (where `process` is undefined).
 */

import indexJson from "../assets.index.json" with { type: "json" };

/** Semantic family of an indexed asset. */
export type AssetMediaKind = "image" | "vector" | "video" | "audio" | "font";

/** One resolved asset record from the canonical index. */
export interface AssetIndexEntry {
  /** Stable id: POSIX package-relative path without the media extension. */
  id: string;
  /** Semantic family (image/vector/video/audio/font). */
  kind: AssetMediaKind;
  /**
   * Owning game slug, or `null` for shared/brand/universe assets. Derived from
   * the top-level `games/<slug>/` directory by the generator, so it is a plain
   * string (not the playable-only `GameSlug` union) — `warline` and any future
   * non-playable game dir are valid values.
   */
  game: string | null;
  /** Package-relative path (with extension), for dev/build tooling. */
  path: string;
  /** CDN-relative path, joined onto a base origin for deployed runtime. */
  cdnPath: string;
  /** IANA media (MIME) type, e.g. `image/webp`. */
  mediaType: string;
  /** File size in bytes. */
  bytes: number;
  /** Hex SHA-256 of the file contents, for drift/integrity checks. */
  sha256: string;
  /** Intrinsic width in px, where the format exposes it. */
  width?: number;
  /** Intrinsic height in px, where the format exposes it. */
  height?: number;
  /** Provenance note, where recorded in `asset-provenance.json`. */
  provenance?: string;
  /** License note, where recorded in `asset-provenance.json`. */
  license?: string;
}

/** The committed canonical asset index document. */
export interface AssetIndex {
  $schema?: string;
  version: string;
  generator?: string;
  note?: string;
  /** Default CDN origin; overridable at runtime via `ASSET_BASE_URL`/`baseUrl`. */
  cdnBase: string;
  assetCount: number;
  assets: AssetIndexEntry[];
}

/** Options for resolving a CDN URL. */
export interface ResolveUrlOptions {
  /** Explicit CDN origin; wins over env/manifest defaults. */
  baseUrl?: string;
}

/** Filter for {@link listAssets}. */
export interface AssetIndexFilter {
  game?: string | null;
  kind?: AssetMediaKind;
  mediaType?: string;
}

/** The canonical asset index, loaded from `assets.index.json`. */
export const assetIndex: AssetIndex = indexJson as unknown as AssetIndex;

const byId = new Map<string, AssetIndexEntry>(assetIndex.assets.map((a) => [a.id, a]));
const byPath = new Map<string, AssetIndexEntry>(assetIndex.assets.map((a) => [a.path, a]));

/** Read `ASSET_BASE_URL` without assuming a Node `process` global exists. */
function envBaseUrl(): string | undefined {
  const proc = (globalThis as { process?: { env?: Record<string, string | undefined> } }).process;
  const value = proc?.env?.ASSET_BASE_URL;
  return value && value.length > 0 ? value : undefined;
}

/** Look up an index entry by its stable id. */
export function getAssetEntry(id: string): AssetIndexEntry | undefined {
  return byId.get(id);
}

/** Look up an index entry by its package-relative path. */
export function getAssetEntryByPath(path: string): AssetIndexEntry | undefined {
  return byPath.get(path);
}

/**
 * The package-relative path for an asset id, or `undefined` if unknown. Use for
 * dev/build tooling that reads bytes from `packages/assets`.
 */
export function resolveAssetPath(id: string): string | undefined {
  return byId.get(id)?.path;
}

/**
 * The effective CDN origin: explicit `baseUrl`, else `ASSET_BASE_URL`, else the
 * manifest's baked-in {@link AssetIndex.cdnBase}.
 */
export function assetBaseUrl(opts: ResolveUrlOptions = {}): string {
  return opts.baseUrl ?? envBaseUrl() ?? assetIndex.cdnBase;
}

/**
 * The absolute CDN URL for an asset id, or `undefined` if unknown. Tolerates a
 * trailing slash on the base and a leading slash on the cdn path.
 */
export function resolveAssetUrl(id: string, opts: ResolveUrlOptions = {}): string | undefined {
  const entry = byId.get(id);
  if (!entry) return undefined;
  const base = assetBaseUrl(opts).replace(/\/+$/, "");
  const path = entry.cdnPath.replace(/^\/+/, "");
  return `${base}/${path}`;
}

/** Every entry, optionally filtered by game, kind, and/or media type. */
export function listAssets(filter: AssetIndexFilter = {}): AssetIndexEntry[] {
  return assetIndex.assets.filter((a) => {
    if (filter.game !== undefined && a.game !== filter.game) return false;
    if (filter.kind !== undefined && a.kind !== filter.kind) return false;
    if (filter.mediaType !== undefined && a.mediaType !== filter.mediaType) return false;
    return true;
  });
}
